### PR TITLE
Single-container version

### PR DESCRIPTION
**Pull request by chemikadze**
Depends on https://github.com/qubell-bazaar/dockerfiles/pull/3
Breaks backward compatibility. There is a compatibility pr https://github.com/qubell-bazaar/component-war-docker/pull/5 that changes WAR interface in the same way.

### CODE REVIEW

**Comment by dornatsky** [comment]
compatibility between what?

**Comment by chemikadze** [comment]
With https://github.com/qubell-bazaar/component-petclinic-docker/issues/5

**Comment by chemikadze** [comment]
@dornatsky Did you forgot this by mistake?

**Comment by dornatsky** [comment]
Yes.
We still need pet clinic to work in a cluster of more than one machine

**Comment by chemikadze** [comment]
Note that reconfiguring branches will look like this because of http endpoint component behavior
sunset_orange_petclinic_on_docker
Probably we need to fix it.

**Comment by dornatsky** [comment]
Does it still work despite the error? Will it work on one machine?

**Pull request merged**
